### ISSUE TITLE
Answers in Spanish

### ISSUE THREAD

**Issue by marcelofprado** [maritaca-ai/maritalk-api#1]
After using the Maritaca API for a couple of days, we noticed some answers in Spanish.

![image](https://github.com/maritaca-ai/maritalk-api/assets/45832968/a40e1481-3fe8-4817-9893-8cf22bc818b2)

**Comment by rodrigo-f-nogueira** [comment]
Hi @marcelofprado, could you please provide an example so we can debug?

**Comment by marcelofprado** [comment]
Did not record the exact context instructions, but the prompt was: 

"liste algumas operadoras que vendam número 0800"

**Comment by rodrigo-f-nogueira** [comment]
Closing this due to the release of the new Sabiá-2, which is served under the MariTalk webchat. Please let us know if the problem persists!
