### ISSUE TITLE
API not returning

### ISSUE THREAD

**Issue by marcelofprado** [maritaca-ai/maritalk-api#2]
It appears that the API chat endpoint does not have a timeout logic, and sometimes it stucks in a request and does not return anything for a long time.

**Comment by rodrigo-f-nogueira** [comment]
Hi @marcelofprado, thanks for letting us know. Could you please try again? The service should be stable now.

**Comment by rodrigo-f-nogueira** [comment]
I've just had the same issue and we are investigating. Thanks for letting us know.

**Comment by willianfco** [comment]
Hello, i've been encountering the same issue for the past few days. Some requests seem to hang for hours without returning any results. Any insights or solutions would be greatly appreciated.

**Comment by rodrigo-f-nogueira** [comment]
Closing this as we haven't observed this behaviour recently.
