### ISSUE TITLE
Does the API support streaming?

### ISSUE THREAD

**Issue by gbaptista** [maritaca-ai/maritalk-api#33]
Does the API (https://chat.maritaca.ai/api/chat/inference) provide streaming capabilities via [Server-Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) or something similar?

**Comment by rodrigo-f-nogueira** [comment]
Hi @gbaptista, not yet but it will be available soon.

**Comment by thiagolaitz** [comment]
Hi @gbaptista, we have just released a new version of our library that supports streaming via Server-Sent Events (SSE) [link](https://github.com/maritaca-ai/maritalk-api?tab=readme-ov-file#streaming)!
