### ISSUE TITLE
API para ambiente de teste

### ISSUE THREAD

**Issue by Uriel29** [maritaca-ai/maritalk-api#34]
Olá! 

Fui testar mais uma vez a API! 

Mas agora precisa pagar antes de testar! 
Sugiro a criação de um ambiente, ou API só para testes! 
Dando uma boa quantidade de tokens. 

Para depois CASO a ferramenta resolva os problemas possamos mudar para a versão comercial de produção da API.

**Comment by rodrigo-f-nogueira** [comment]
Olá Uriel, ao assinar a MariTalk API, você ganha 20 reais de créditos, que equivalem à 4 milhões de tokens.
