### ISSUE TITLE
Funcionalidade de Rastreamento de Tokens

### ISSUE THREAD

**Issue by arthurcbaia** [maritaca-ai/maritalk-api#42]
Oi gente, tudo bem?
Gostaria de propor uma melhoria para este repositório que acredito que poderia melhorar significativamente a sua funcionalidade e usabilidade. Especificamente, acho que traria grande valor a adição de um recurso que rastreie a quantidade de tokens utilizados no prompt e os tokens gerados.
Essa adição permitiria um detalhamento do uso de tokens, o que seria particularmente útil para entender e otimizar o desempenho do sistema e dos custos. Um bom exemplo de como a saída poderia parecer no formato JSON, que segue o padrão [OpenAI](https://platform.openai.com/docs/guides/text-generation/chat-completions-response-format), seria:
```json
"usage": {
    "completion_tokens": 17,
    "prompt_tokens": 57,
    "total_tokens": 74
}
```

**Comment by rodrigo-f-nogueira** [comment]
Olá Arthur, muito obrigado pela sugestão. Iremos implementar essa funcionalidade. Enquanto não fica pronta, você pode "manualmente" fazer a contagem de tokens consumidos usando o tokenizador da maritalk, disponível na HuggingFace: https://huggingface.co/maritaca-ai/maritalk-tokenizer-large

**Comment by arthurcbaia** [comment]
Obrigado pela resposta e pela sugestão.

**Comment by rodrigo-f-nogueira** [comment]
Funcionalidade implementada na v0.1.9.
Obrigado novamente pela sugestão!
