### ISSUE TITLE
Melhor prática para enviar textos longos

### ISSUE THREAD

**Issue by DaniloOliveira28** [maritaca-ai/maritalk-api#45]
Estou usando a maritalk-api para produzir resumos. Alguns dos meus textos possuem mais que 7mil tokens, dessa forma, quando eu tento enviar o texto, a api me retorna:

```
Detail: The messages submitted are too long: 11697 tokens. The maximum supported is 7000 tokens
```

Qual procedimento vocês sugerem que eu posso adotar para enviar um texto com no máximo 7000 tokens?

**Comment by rodrigo-f-nogueira** [comment]
Olá @DaniloOliveira28, infelizmente não conheço nenhuma técnica eficaz para esse problema. Mas gostaria de sugerir uma bem simples: Se a tarefa consiste em fazer resumos, as vezes a informação mais importante está no começo e fim do texto. Assim, concatenar os primeiros ~3000 tokens com os ultimos 3000 tokens pode trazer bons resultados. 

A propósito, o numero máximo agora está em 8000 tokens. Além disso, em breve suportaremos 32k tokens.
