### ISSUE TITLE
Exemplos com LangChain não estão funcionando

### ISSUE THREAD

**Issue by anapaulagomes** [maritaca-ai/maritalk-api#64]
Olá, pessoal. Tentei executar os exemplos com Langchain mas o notebook tem alguns erros. O primeiro, é o parâmetro do modelo que está faltando no objeto `maritalk.MariTalk`. Depois, o seguinte erro na validação do conteúdo da mensagem (apesar de ser uma string). Não tive como ir muito longe mas fica aqui o registro. Obrigada!

```
ValidationError: 2 validation errors for AIMessage
content
  str type expected (type=type_error.str)
content
  value is not a valid list (type=type_error.list)
````

Notebook: https://github.com/maritaca-ai/maritalk-api/blob/main/examples/api/maritalk_langchain.ipynb

**Comment by rodrigo-f-nogueira** [comment]
Olá @anapaulagomes 

Desculpe, este colab está desatualizado. Vamos remove-lo.

Está é a documentação atualizada: https://python.langchain.com/docs/integrations/chat/maritalk

**Comment by rodrigo-f-nogueira** [comment]
Fechando pois o link foi atualizado para documentação correta.
