### ISSUE TITLE
HTTP Resquest não funciona

### ISSUE THREAD

**Issue by devalexandre** [maritaca-ai/maritalk-api#69]
```sh 
curl --location 'https://chat.maritaca.ai/api/chat/inference' \
--header 'accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: key ****$f410151375330261' \
--data '{
  "messages": [
    {
      "role": "string",
      "content": "string"
    }
  ],
  "chat_mode": true,
  "max_tokens": 1,
  "model": "sabia-2-small",
  "do_sample": true,
  "temperature": 0.7,
  "top_p": 0.95,
  "repetition_penalty": 1,
  "stopping_tokens": [
    "string"
  ],
  "stream": false,
  "num_tokens_per_message": 4
}'
``` 
{
    "detail": "Sorry, you need to be a premium user to use MariTalk via API. Make sure that your account is active."
}

o plano esta ativo, mas simplismente nao funciona

![image](https://github.com/maritaca-ai/maritalk-api/assets/4489558/2c1eeaf7-ea75-44c6-a7eb-0929f9eb514a)

**Comment by rodrigo-f-nogueira** [comment]
Obrigado por avisar, estamos verificando o problema

**Comment by ZanezZephyrs** [comment]
oi @devalexandre . O problema que você estava tendo era um bug em relação ao header de autorização, deveria estar funcionando normalmente agora. 

Obrigado por avisar e se continuar tendo algum problema é so falar.

**Comment by devalexandre** [comment]
legal, mas encontri outro detalhe, nao esta retornando a resposta.

payload:

```json
{
  "messages": [
      {"role": "user", "content": "Você pode me falar quanto é 25 + 27?"}
  ],
  "chat_mode": true,
  "max_tokens": 1,
  "model": "sabia-2-small",
  "do_sample": true,
  "temperature": 0.6,
  "top_p": 0.95,
  "repetition_penalty": 1,
  "stopping_tokens": [],
  "stream": false,
  "num_tokens_per_message": 4
}
``` 

response
```json
{
    "answer": " ",
    "usage": {
        "completion_tokens": 1,
        "prompt_tokens": 19,
        "total_tokens": 20
    },
    "model": "sabia-2-small"
}
```

**Comment by piresramon** [comment]
Oi @devalexandre. Nesse caso, acho que falta você aumentar o max_tokens. Como está setado como 1, o modelo gerou 1 token e parou.
